version: '3.3'
services:
  bitcoin-abc-testnet:
    build:
      context: ./
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"
    ports:
      - 20009:20009
      - 20008:20008
    restart: unless-stopped
    volumes:
      - bitcoin-abc-testnet:/home/bitcoin/.bitcoin
      - ./bitcoin.conf:/home/bitcoin/.bitcoin/bitcoin.conf

volumes:
  bitcoin-abc-testnet:
