version: '3.3'
services:
  bitcoin-abc-testnet:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bitcoind -testnet -txindex=0 -listen=1 -server=1 -irc=1 -upnp=1 -port=20008 -rpcbind=0.0.0.0 -rpcallowip=127.0.0.1 -rpcallowip=172.0.0.0/8 -rpcallowip=212.70.175.0/24 -whitelist=172.0.0.0/8 -whitelist=212.70.175.0/24 -rpcport=20009 -rpcuser=username -rpcpassword=password -printtoconsole=1
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"
    ports:
      - 20009:20009
      - 20008:20008
    restart: unless-stopped
    volumes:
      - bitcoin-abc-testnet:/home/bitcoin/.bitcoin

volumes:
  bitcoin-abc-testnet:
